apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-command-center-ui
  namespace: suite
spec:
  template:
    spec:
      containers:
        - name: ui
          ports:
            - name: http
              containerPort: 80
