apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-command-center-ui
spec:
  template:
    spec:
      containers:
        - name: ui
          ports:
            - containerPort: 3000
              name: http

