apiVersion: v1
kind: ServiceAccount
metadata:
  name: suite-command-center-api-shim
  namespace: suite
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suite-command-center-api-shim-ro
rules:
  # cluster-scoped + namespaced read-only
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets", "replicasets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  # newer events API (some clusters use it)
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suite-command-center-api-shim-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: suite-command-center-api-shim-ro
subjects:
  - kind: ServiceAccount
    name: suite-command-center-api-shim
    namespace: suite
