apiVersion: apps/v1
kind: Deployment
metadata:
  name: suite-command-center-api-shim
  namespace: suite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: suite-command-center-api-shim
  template:
    metadata:
      labels:
        app: suite-command-center-api-shim
    spec:
      serviceAccountName: suite-command-center-api-shim
      containers:
        - name: api
          image: python:3.12-slim
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8000"
            - name: APP_NAME
              value: "suite-command-center-api-shim"
          ports:
            - name: http
              containerPort: 8000
          command: ["python", "/app/server.py"]
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: code
              mountPath: /app
              readOnly: true
      volumes:
        - name: code
          configMap:
            name: suite-command-center-api-shim
