apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suite-command-center
  namespace: suite
spec:
  interval: 10m
  timeout: 10m

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      chart: ./apps/suite/command-center/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m
      reconcileStrategy: ChartVersion
      version: "*"

  values:
    api:
      image:
        repository: registry.suite.home.arpa:5000/suite-command-center-api
        tag: latest
      port: 8000

    ui:
      image:
        repository: registry.suite.home.arpa:5000/suite-command-center-ui
        tag: latest
      port: 80

    service:
      apiPort: 80
      uiPort: 80
