apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suite-command-center
  namespace: suite
spec:
  interval: 10m
  timeout: 10m

  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3

  chart:
    spec:
      # This is the path INSIDE the GitRepository artifact
      chart: ./apps/suite/command-center/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 10m

  values:
    image:
      repository: registry.suite.home.arpa:5000/suite-command-center-api
      tag: latest
    uiImage:
      repository: registry.suite.home.arpa:5000/suite-command-center-ui
      tag: latest
    service:
      port: 80
    ingress:
      enabled: false
