# HelmRelease for Command Center
#
# NOTE: Image tags are managed via the patch file at:
#   patches/patch-helmrelease-values.yaml
#
# The patch file contains image automation markers that allow Flux to
# automatically update image tags when new builds are pushed to the registry.
#
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: suite-command-center
  namespace: suite
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/suite/command-center/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    api:
      image:
        repository: registry.suite.home.arpa:5000/suite-command-center-api
        tag: "latest"
        pullPolicy: Always

    ui:
      image:
        repository: registry.suite.home.arpa:5000/suite-command-center-ui
        tag: "20260114-1050"
        pullPolicy: IfNotPresent
      service:
        port: 80
        targetPort: 3000

    serviceAccount:
      create: true
      name: suite-command-center-api

    rbac:
      create: true
