apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-api-shim-egress-k8s
  namespace: suite
spec:
  podSelector:
    matchLabels:
      app: suite-command-center-api-shim
  policyTypes: ["Egress"]
  egress:
    # DNS to CoreDNS (k3s typically labels it k8s-app=kube-dns)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - { protocol: UDP, port: 53 }
        - { protocol: TCP, port: 53 }

    # Kubernetes API via the in-cluster 'kubernetes' service IP
    - to:
        - ipBlock:
            cidr: 10.43.0.1/32
      ports:
        - { protocol: TCP, port: 443 }
