apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: observe
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      # Newer versions remove PodSecurityPolicy entirely
      version: 11.7.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observe

  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback

  values:
    # Keep PrometheusRule out of this chart (we'll create a real PrometheusRule CR instead)
    prometheusRule:
      enabled: false

    # Create ServiceMonitors that kube-prometheus-stack will actually pick up
    serviceMonitor:
      selfMonitor:
        enabled: true
        labels:
          release: kube-prometheus-stack

      enabled: true
      defaults:
        module: http_2xx
        interval: 30s
        scrapeTimeout: 30s
        labels:
          release: kube-prometheus-stack
      targets:
        - name: command-center-healthz
          url: https://command-center.allenwmoorejr.org/healthz
          labels:
            app: command-center
        - name: command-center-root
          url: https://command-center.allenwmoorejr.org/
          labels:
            app: command-center
