apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: observe
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 5.8.2
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: observe
  values:
    # 1) K8s >=1.25: PSP is gone, so DO NOT render it
    pspEnabled: false

    # 2) Have Prometheus Operator pick these up (kube-prometheus-stack default selector)
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
      defaults:
        interval: 30s
        scrapeTimeout: 10s
        module: http_2xx
      targets:
        - name: command-center-ui
          url: https://command-center.allenwmoorejr.org/
        - name: command-center-api-healthz
          url: https://command-center.allenwmoorejr.org/healthz

    # 3) Escape Prometheus templating so Helm tpl doesn't try to evaluate $labels/$value
    prometheusRule:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
      rules:
        - alert: CommandCenterEndpointDown
          expr: probe_success{instance=~"https://command-center\\.allenwmoorejr\\.org.*"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: Command Center endpoint down
            description: 'Probe failed for {{ "{{" }} $labels.instance {{ "}}" }}'

        - alert: CommandCenterEndpointSlow
          expr: probe_duration_seconds{instance=~"https://command-center\\.allenwmoorejr\\.org.*"} > 2
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Command Center endpoint slow
            description: '{{ "{{" }} $labels.instance {{ "}}" }} latency is {{ "{{" }} $value {{ "}}" }}s'
