apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: suite-command-center-api-read
subjects:
  - kind: ServiceAccount
    name: suite-command-center-api
    namespace: suite
roleRef:
  kind: ClusterRole
  name: suite-command-center-api-read
  apiGroup: rbac.authorization.k8s.io
