apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: suite-command-center-api-read
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]
