apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: clm
  namespace: suite
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/suite/clm/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    ui:
      image:
        repository: registry.suite.home.arpa:5000/clm
        tag: "20260126-182203" # {"$imagepolicy": "flux-system:clm:tag"}
        pullPolicy: IfNotPresent
      env:
        CHANNEL_ID: "UCwFzqkthzt9qqRgsmHWsQ0Q"
      service:
        port: 80
        targetPort: 3000
